mysite/home/urls.py
# Admin Id :- super@123
# Admin Pass :- super111

from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.About, name='about'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.Logout, name='logout'),
    path('Packages/', views.packages, name='packages'),
    path('booking/', views.Booking, name='booking'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('packages/<str:slug>', views.Packages, name='packages')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
# Admin Id :- super@123
# Admin Pass :- super111

from django.contrib import admin
from django.urls import path
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls)
]

mysite/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(null=True, blank=True, upload_to='profile-images/', default='avatar.png')
    # date = models.DateField(default='01-01-2022')

class Contact(models.Model):
    name=models.CharField(max_length=20)
    email=models.CharField(max_length=20)
    message=models.TextField()
    date=models.DateField()

    def __str__(self):
        return self.name

class Register(models.Model):
    username=models.CharField(max_length=20)
    email=models.CharField(max_length=20)
    pass1=models.CharField(max_length=20)
    pass2=models.CharField(max_length=20)
    date=models.DateField()

    def __str__(self):
        return self.username


class Tour(models.Model):
    title = models.CharField(max_length=50, null=False)
    slug = models.CharField(max_length=50, null=False,unique=True)
    description = models.CharField(max_length=1000, null=True)
    price = models.IntegerField(null=False)
    discount = models.IntegerField(null=False, default = 0)
    active = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to='tour-images/')
    date = models.DateTimeField(auto_now_add=True)
    day = models.IntegerField(null=True)
    night = models.IntegerField(null=True)
    people = models.IntegerField(null=True)


    def __str__(self):
        return self.title


class TourProperty(models.Model):
    description = models.CharField(max_length=1000, null=False)
    Tour = models.ForeignKey(Tour, null=False, on_delete=models.CASCADE)

    class Meta:
        abstract = True

class Tag(TourProperty):
    pass

class Program(TourProperty):
    pass

class Gallary(models.Model):
    Tour = models.ForeignKey(Tour, null=True, on_delete=models.CASCADE)
    description = models.ImageField(upload_to='Gallary/')

class Subject(models.Model):
    Tour = models.ForeignKey(Tour, null=True, on_delete=models.CASCADE)
    main_description = models.CharField(max_length=200, null=True)
    day_count = models.IntegerField(null=True)
    subj_title = models.CharField(max_length=50, null=False)
    subj_description = models.CharField(max_length=200, null=False)


# ===================== Booking =====================
class TourBooking(models.Model):
    firstname_booking=models.CharField(max_length=20)
    lastname_booking=models.CharField(max_length=20)
    email_booking=models.CharField(max_length=20)
    phone_number=models.CharField(max_length=10)
    firstname_card=models.CharField(max_length=20)
    card_number=models.CharField(max_length=12)
    expire_month= models.DateField()
    expire_year= models.DateField()
    ccv= models.CharField(max_length=3)

mysite/home/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User, auth
from datetime import datetime
from .models import Contact
from .models import Register
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout,login as user_login
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from home.models import Tour, Tag, Program, Gallary, Subject, Profile, Register, TourBooking

# Create your views here.
#All pages Links.
# razorpay_client = razorpay.Client(
#     auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))


def index(request):
    return render(request, "index.html",{})

def About(request):
    return render(request, "about.html",{})

def register(request):
    if request.method == 'POST':
        first_name = request.POST.get('registerFirstName')
        last_name = request.POST.get('registerLastName')
        email = request.POST.get('registerEmail')
        username = request.POST.get('registerUsername')
        password = request.POST.get('registerPassword')
        # Check if the username is already taken
        if User.objects.filter(username=username).exists():
            return render(request, 'register.html', {'error_message': 'Username is already taken'})
        if User.objects.filter(email=email).exists():
            return render(request, 'register.html', {'error_message': 'Email is already use'})

        # Create the user
        else:
            user = User.objects.create_user(username=username, email=email, password=password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()

            return redirect('login')  # Redirect to the login page after successful registration

    return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('loginUsername')
        password = request.POST.get('loginPassword')
        user = authenticate(username=username, password=password)
        if user is not None:
            # user_login(self.request, user):
            user_login(request,user)
            if user.is_superuser:
                # Redirect superuser to admin panel
                return redirect('/admin/')
            return redirect('index')  # Redirect to the home page after successful login
        else:
            return render(request, "login.html", {'error_message': 'Invalid username or password'})
    return render(request, "login.html")

def profile(request):
    return render(request, 'profile.html')

def thankyou(request):
    return render(request, 'thankyou.html')


@login_required
def profile(request):
    if request.method == "POST":
        firstname = request.POST.get('first_name')
        lastname = request.POST.get('last_name')
        username = request.POST.get('username')
        image = request.FILES.get('image_up_lode')
        email = request.POST.get('email')
        # dob = request.POST.get('d_o_b')
        # Update User model
        user = User.objects.get(username=request.user.username)
        user.first_name = firstname
        user.last_name = lastname
        user.username = username
        user.email = email
        user.save()

        # Update or create Profile instance
        profile_instance, created = Profile.objects.get_or_create(user=request.user)
        print(image)
        if image:
            profile_instance.profile_picture = image
        profile_instance.save()
        return redirect('index')
    # contex of profile page
    context = {
    }
    return render(request, 'profile.html',context)

def Logout(request):
    logout(request)
    return redirect('login')


def Booking(request):
    return render(request, "booking.html",{})

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        contact = Contact(name=name, email=email, message=message, date=datetime.today())
        # return redirect('contact')
        contact.save()
        return redirect('contact')
    return render(request, "contact.html",{})

def faq(request):
    return render(request, "faq.html",{})

def testimonial(request):
    return render(request, "testimonial-page.html",{})

def packages(request):

    tour = Tour.objects.all()

    return render(request, "packages.html", context={'tour' : tour})

def Packages(request, slug):

    tour = Tour.objects.get(slug = slug)
    context = {
        "tour" : tour
    }
    return render(request, "package-detail.html", context=context)


def booking(request):
    if request.method == 'POST':
        firstname_booking = request.POST.get('firstname_booking')
        lastname_booking = request.POST.get('lastname_booking')
        email_booking = request.POST.get('email_booking')
        phone_number = request.POST.get('phone_number')
        firstname_card = request.POST.get('firstname_card')
        card_number = request.POST.get('card_number')
        expire_month = request.POST.get('expire_month')
        expire_year = request.POST.get('expire_year')
        ccv = request.POST.get('ccv')

        if User.objects.filter(username=username).exists():
            return render(request, 'register.html', {'error_message': 'Username is already taken'})

        booking = TourBooking(firstname_booking=firstname_booking, lastname_booking=lastname_booking,
                          email_booking=email_booking, phone_number=phone_number,
                          firstname_card=firstname_card, card_number=card_number,
                          expire_month=expire_month, expire_year=expire_year,
                          ccv=ccv, date=datetime.today())
        booking.save()
    return render(request, 'register.html',{})

mysite/home/templates/base.html
{% include 'header.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

mysite/home/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

         <main id="content" class="site-main">
            <!-- Inner Banner html start-->
            <section class="inner-banner-wrap">
               <div class="inner-baner-container" style="background-image: url('http://127.0.0.1:8000/static/assets/images/slider-banner-1.jpg');">
                  <div class="container">
                     <div class="inner-banner-content">
                        <h1 class="inner-title">Contact us</h1>
                     </div>
                  </div>
               </div>
               <div class="inner-shape"></div>
            </section>
            <!-- Inner Banner html end-->
            <!-- contact form html start -->
            <div class="contact-page-section">
               <div class="contact-form-inner">
                  <div class="container">
                     <div class="row">
                        <div class="col-md-6">
                           <div class="contact-from-wrap">
                              <div class="section-heading">
                                 <h5 class="dash-style">GET IN TOUCH</h5>
                                 <h2>CONTACT US TO GET MORE INFO</h2>
                                 <p>Aperiam sociosqu urna praesent, tristique, corrupti condimentum asperiores platea ipsum ad arcu. Nostrud. Esse? Aut nostrum, ornare quas provident laoreet nesciunt odio voluptates etiam, omnis.</p>
                              </div>
                              <form class="contact-from" method="POST">
                                 {% csrf_token %}
                                 <p>
                                    <input type="text" name="name" placeholder="Your Name*">
                                 </p>
                                 <p>
                                    <input type="email" name="email" placeholder="Your Email*">
                                 </p>
                                 <p>
                                    <textarea rows="8" name="message" placeholder="Your Message*"></textarea>
                                 </p>
                                 <p>
                                    <input type="submit" name="submit" value="SUBMIT MESSAGE">
                                 </p>
                              </form>
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="contact-detail-wrap">
                              <h3>Need help ?? Feel free to contact us !</h3>
                              <p>Our travel agency is here to make your dream vacation a reality. Whether you're planning a solo adventure, a romantic getaway, or a family trip, we've got you covered. Contact us today and let our expert team create a personalized travel experience just for you. Your next adventure awaits!"</p>
                              {% comment %} //<p>Nostra doloribus blandit et semper ultrices, quibusdam dignissimos! Netus recusandae, rerum cupidatat. Perferendis aptent wisi.</p> {% endcomment %}
                              <div class="details-list">
                                 <ul>
                                    <li>
                                       <span class="icon">
                                          <i class="fas fa-map-signs"></i>
                                       </span>
                                       <div class="details-content">
                                          <h4>Location Address</h4>
                                          <span>Mumbai</span>
                                       </div>
                                    </li>
                                    <li>
                                       <span class="icon">
                                          <i class="fas fa-envelope-open-text"></i>
                                       </span>
                                       <div class="details-content">
                                          <h4>Email Address</h4>
                                          <span>wanderly@domain.com</span>
                                       </div>
                                    </li>
                                    <li>
                                       <span class="icon">
                                          <i class="fas fa-phone-volume"></i>
                                       </span>
                                       <div class="details-content">
                                          <h4>Phone Number</h4>
                                          <span>Telephone: 619-270-8578 / Mobile: +91 1198712388</span>
                                       </div>
                                    </li>
                                 </ul>
                              </div>
                              <div class="contct-social social-links">
                                 <h3>Follow us on social media..</h3>
                                 <ul>
                                    <li><a href="#"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <!-- contact form html end -->
         </main>
{% endblock %}

mysite/home/templates/footer.html
{% load static %}
<!--Footer Start-->
<footer class="site-footer footer-primary" id="colophon">
    <div class="top-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <aside class="widget widget_text">
                        <h3 class="widget-title">
                            About Travel
                        </h3>
                        <div class="textwidget widget-text">


"Ready to explore the world? Contact us today and let’s make your travel dreams come true. Your adventure is just a call away!"
                        </div>
                        <div class="award-img">
                            <a href="#"><img alt="" src="static/assets/images/logo6.png"></a>
                            <a href="#"><img alt="" src="static/assets/images/logo2.png"></a>
                        </div>
                    </aside>
                </div>
                <div class="col-lg-4 col-md-6">
                    <aside class="widget widget_text">
                        <h3 class="widget-title">CONTACT INFORMATION</h3>
                        <div class="textwidget widget-text">
                            Connect with us on social media for the latest travel tips and deals!.
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fas fa-phone-alt"></i>
                                        +91 977259912
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fas fa-envelope"></i>
                                        wanderly@domain.com
                                    </a>
                                </li>
                                <li>
                                    <i class="fas fa-map-marker-alt"></i>
                                    Mumbai
                                </li>
                            </ul>
                        </div>
                    </aside>
                </div>
                <div class="col-lg-4 col-md-6">
                    <aside class="widget widget_newslatter">
                        <h3 class="widget-title">SUBSCRIBE US</h3>
                        <div class="widget-text">
                            "Stay in the loop! Subscribe to our newsletter for exclusive travel deals, tips, and destination guides. 
                        </div>
                        <form class="newslatter-form">
                            <input name="s" placeholder="Your Email.." type="email">
                            <input name="s" type="submit" value="SUBSCRIBE NOW">
                        </form>
                    </aside>
                </div>
            </div>
        </div>
    </div>
    <div class="buttom-footer">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-5">
                    <div class="footer-menu">
                        <ul>
                            <li>
                                <a href="#">Privacy Policy</a>
                            </li>
                            <li>
                                <a href="#">Term & Condition</a>
                            </li>
                            <li>
                                <a href="#">FAQ</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2 text-center">
                    <div class="footer-logo">
                        <a href="#"><img alt="" src="static/assets/images/w1.png"></a>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="copy-right text-right">Copyright © 2024 Travele. All rights reserveds</div>
                </div>
            </div>
        </div>
    </div>
</footer>

<!--Footer End-->
<a class="to-top-icon" href="#" id="backTotop">
    <i class="fas fa-chevron-up"></i>
</a>
<!-- custom search field html -->
<div class="header-search-form">
    <div class="container">
        <div class="header-search-container">
            <form class="search-form" method="get" role="search">
                <input name="s" placeholder="Enter your text..." type="text">
            </form>
            <a class="search-close" href="#">
                <i class="fas fa-times"></i>
            </a>
        </div>
    </div>
</div>
<!-- header html end -->
</div>

<!-- JavaScript -->
<script src="{% static 'assets/js/jquery.js' %}"></script>
<script src="{% static 'http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/vendors/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/vendors/countdown-date-loop-counter/loopcounter.js' %}"></script>
<script src="{% static 'assets/js/jquery.counterup.js' %}"></script>
<script src="{% static 'assets/vendors/modal-video/jquery-modal-video.min.js' %}"></script>
<script src="{% static 'assets/vendors/masonry/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendors/lightbox/dist/js/lightbox.min.js' %}"></script>
<script src="{% static 'assets/vendors/slick/slick.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'assets/js/custom.min.js' %}"></script>
</body>
</html>

mysite/home/templates/package-detail.html
{% extends 'base.html' %}
{% load tour_custom_tags %}
{% load static %}
{% block content %}

<main class="site-main" id="content">
    <!-- Inner Banner html start-->
    <section class="inner-banner-wrap">
        <div class="inner-baner-container" style="background-image: url(assets/images/inner-banner.jpg);">
            <div class="container">
                <div class="inner-banner-content">
                    <h1 class="inner-title">Tour Packages</h1>
                </div>
            </div>
        </div>
        <div class="inner-shape"></div>
    </section>

    <!--    <section class="activity-section invisible">-->
    <!--        <div class="container-fluid">-->
    <!--            <p>Selected Tour : {{tour.title}}</p>-->
    <!--            <p>Selected Tour : {{tour.description}}</p>-->
    <!--            <p>Selected Tour : {{tour.price}}</p>-->
    <!--            <p>Selected Tour : {{tour.discount}}</p>-->
    <!--            <p>Selected Tour : {{tour.active}}</p>-->
    <!--            <p>Selected Tour : {{tour.thumbnail}}</p>-->
    <!--            <p>Selected Tour : {{tour.date}}</p>-->
    <!--            <p>Selected Tour : {{tour.day}}</p>-->
    <!--            <p>Selected Tour : {{tour.night}}</p>-->
    <!--            <p>Selected Tour : {{tour.people}}</p>-->
    <!--            <p>Selected Tour : {{tour.tag_set.all}}</p>-->
    <!--            <p>Selected Tour : {{tour.program_set.all}}</p>-->
    <!--            <p>Selected Tour : {{tour.gallary_set.all}}</p>-->
    <!--            <p>Selected subject : {{tour.subject_set.all}}</p>-->
    <!--        </div>-->
    <!--    </section>-->
    <!--    </section>-->


    <div class="single-tour-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="single-tour-inner">
                        <h2>{{tour.title}}</h2>
                        <figure class="feature-image">
                            <img alt="" src="{{tour.thumbnail.url}}">
                            <div class="package-meta text-center">
                                <ul>
                                    <li>
                                        <i class="far fa-clock"></i>
                                        {{tour.day}} Days / {{tour.night}} Night
                                    </li>
                                    <li>
                                        <i class="fas fa-user-friends"></i>
                                        People: {{tour.people}}
                                    </li>
                                    <li>
                                        <i class="fas fa-map-marked-alt"></i>
                                        {{tour.title}}
                                    </li>
                                </ul>
                            </div>
                        </figure>
                        <div class="tab-container">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a aria-controls="overview" aria-selected="true" class="nav-link active"
                                       data-toggle="tab"
                                       href="#overview" id="overview-tab" role="tab">TOUR DESCRIPTION</a>
                                </li>
                                <li class="nav-item">
                                    <a aria-controls="program" aria-selected="false" class="nav-link" data-toggle="tab"
                                       href="#program"
                                       id="program-tab" role="tab">PROGRAM</a>
                                </li>

                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div aria-labelledby="overview-tab" class="tab-pane fade show active" id="overview"
                                     role="tabpanel">
                                    <div class="overview-content">
                                        {% for tag in tour.tag_set.all %}
                                        <p>
                                            {{tag.description}}
                                        </p>
                                        {% endfor %}
                                        <div>
                                            {% for prog in tour.program_set.all %}
                                            <li> {{prog.description}}</li>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="program" role="tabpanel">
                                    <div class="itinerary-content">
                                        <h3>Program <span>( {{tour.day}} days )</span></h3>
                                        {% for subject in tour.subject_set.all %}
                                        <p>{{subject.main_description}}</p>
                                        {% endfor %}
                                    </div>
                                    <div class="itinerary-timeline-wrap">
                                        <ul>
                                            <li>
                                                <div class="timeline-content">
                                                    <div class="row">
                                                        {% for subject in tour.subject_set.all %}
                                                        <div class="timeline-content">
                                                            <div class="day-count">Day
                                                                <span>{{subject.day_count}}</span></div>
                                                            <h4>{{subject.subj_title}}</h4>
                                                            <p>{{subject.subj_description}}</p>
                                                        </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="single-tour-gallery">
                            <h3>GALLERY / PHOTOS</h3>
                            <div class="single-tour-slider">
                                {% for gallary in tour.gallary_set.all %}
                                <div class="single-tour-item">
                                    <figure class="feature-image">
                                        <img alt="" src="{{gallary.description.url}}">
                                    </figure>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="sidebar">
                        <div class="package-price">
                            <h5 class="price">
                                <span>{% cal_sellprice tour.price tour.discount as value %}{{value|rupee}}</span> / per
                                person
                            </h5>
                        </div>

                        <div class="widget-bg information-content text-center">
                            <h5>TRAVEL TIPS</h5>
                            <h3>NEED TRAVEL RELATED TIPS & INFORMATION</h3>
                            <p>Mollit voluptatem perspiciatis convallis elementum corporis quo veritatis aliquid
                                blandit, blandit torquent, odit placeat. </p>
                            <a class="button-primary" href="{% url 'contact' %}">GET A QUOTE</a>
                            <a class="button-primary" href="{% url 'booking' %}">Booking</a>
                        </div>

                        <div class="travel-package-content text-center"
                             style="background-image: url(assets/images/img11.jpg);">
                            <h5>MORE PACKAGES</h5>
                            <h3>OTHER TRAVEL PACKAGES</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus.</p>
                            <ul>
                                <li>
                                    <a href="#"><i class="far fa-arrow-alt-circle-right"></i>Comming Soon</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>

{% endblock %}